# Generated by Django 4.1.7 on 2023-04-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergenralprofile',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='profileImage'),
        ),
    ]
