# Generated by Django 4.1.7 on 2023-03-31 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_medical_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_phoneno', models.IntegerField(blank=True, null=True)),
                ('doctors_phoneno', models.IntegerField(blank=True, null=True)),
                ('hospital_address', models.CharField(blank=True, max_length=255, null=True)),
                ('doctors_option', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('body_part_effected', models.TextField(blank=True, null=True)),
                ('date_of_visit', models.DateField(default=django.utils.timezone.now)),
                ('prescription_img', models.ImageField(null=True, upload_to='images/')),
                ('medical_report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_medical_profile.medicalcondition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('interval', models.IntegerField(blank=True, null=True)),
                ('medicine_img', models.ImageField(null=True, upload_to='images/')),
                ('medical_report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_medical_profile.medicalcondition')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_medical_profile.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
