# Generated by Django 4.1.7 on 2023-04-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_medical_profile', '0002_report_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='medical_report_id',
            new_name='medical_condition_id',
        ),
    ]
