# Generated by Django 4.1.7 on 2023-04-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_medical_profile', '0003_rename_medical_report_id_report_medical_condition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='doctors_phoneno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='hospital_phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
