# Generated by Django 4.1.7 on 2023-04-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_medical_profile', '0005_alter_report_doctors_phoneno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='doctors_phoneno',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='hospital_phoneno',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
