# Generated by Django 4.1.7 on 2023-04-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_medical_profile', '0006_alter_report_doctors_phoneno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='doctors_phoneno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='hospital_phoneno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
