# Generated by Django 4.1.7 on 2023-04-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_medical_profile', '0008_alter_report_prescription_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='prescription_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
