# Generated by Django 4.1.7 on 2023-04-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_medical_profile', '0010_alter_report_prescription_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='ReportImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_medical_profile.report')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_img', models.ImageField(null=True, upload_to='')),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_medical_profile.medicine')),
            ],
        ),
    ]
