# Generated by Django 4.1.7 on 2023-04-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_medical_profile', '0011_alter_medicine_medicine_img_reportimages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimages',
            name='report_img',
            field=models.ImageField(blank=True, null=True, upload_to='newimages'),
        ),
    ]
